#+title: Tahc

* TAHC
Originally a company called Thrakal Harvester Co. that managed & transported itinerant laborers, then got fairly big from tool manufacture. More recently they have shifted almost entirely into automatic steam reapers, threshers, & tractors.
As a result of a shift in Thrakish politics towards deregulation under Archic Representative Krantz Caleb, TAHC has been taking advantage of a number of largely lawless regions mostly in Western Thrakal, Lektos, and the Debrikal shore for resource extraction operations and has invested considerable sums in private security to protect those operations. Now interested in opening the Lacronian market to trade and increasing trade safety in the Gulf, TAHC has partnered with former Cisani assembly member annd now fillibusterer "General" Sprambis Rose to launch an expedition to end the 4th Musagari War by taking, or at least threatening the capital. The army is taking advantage of the intent and capital of the wealthy company and got a contract & is launching an invaion.
* "General" Rose
Sprambis Rose is a Valestherne-educated scion of a rich Cisani family (textile mill owners) and former lawyer-turned-Assembly member for the Lesser Assembly-turned-freebooter and nationalist thought leader.
Shortly after losing election to the Thrakal Assembly, he decided to attempt to destroy the Pirate Republic of Zaquür to set up a pro-Thrakal state using a private army raised mostly with money from political campaign contributions. This was nor particularly successful, but the group found more victory from fighting as more normal mercenaries in service to local warlords & corporations like TAHC.
